---

##################################################################################
#    ////////////////////////// Requirements //////////////////////////
##################################################################################

- name: Download required collections
  local_action: command ansible-galaxy collection install -r {{ role_path }}/requirements.yml
  become: false
  tags:
    - create
    - delete

##################################################################################
#    ////////////////////////// Tasks Includes //////////////////////////
##################################################################################

- name: Precheck for Proxmox Container management
  include_tasks: precheck.yml
  tags:
    - always

- name: Create Proxmox Container {{ container_name }}
  include_tasks: create_container.yml
  tags:
    - create

- name: Create Proxmox VM {{ container_name }}
  include_tasks: create_vm.yml
  tags:
    - createvm

- name: Delete Proxmox Container {{ container_name }}
  include_tasks: delete_container.yml
  tags:
    - delete

##################################################################################
#  ////////////////////////// Finished Proxmox Action //////////////////////////
##################################################################################

- name: Proxmox Container management finished
  debug:
    msg: "Proxmox Container management finished!"
