---

###################################################################################
# Check if the specified Variable Values are valid and defined
###################################################################################

- name: Check if Container Name is defined
  fail:
    msg: "You haven't defined a valid Container Name!"
  when: (container_name == '')
  tags:
    - always

- name: Check if OS Template is defined
  fail:
    msg: "You haven't defined a valid Container Template!"
  when: (container_os_template == '')
  tags:
    - always

- name: Set ssh_public_key
  set_fact:
    ssh_public_key: "{{ lookup('file', 'templates/id_rsa.pub') }}"
  tags:
    - ssh_public_key_from_file

- name: Install needed Python Libraries
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - proxmoxer
    - requests
  tags:
    - always