---

- name: Stop Container {{ container_name }}
  community.general.proxmox:
    vmid: "{{ container_id }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ proxmox_api_host }}"
    state: stopped
    force: yes
    timeout: "{{ action_timeout }}"
  tags:
    - delete

- name: Remove Container {{ container_name }}
  community.general.proxmox:
    vmid: "{{ container_id }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ proxmox_api_host }}"
    state: absent
  tags:
    - delete
